version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-type: production
    reviewers:
      - erunion
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-type: production
    open-pull-requests-limit: 10
    reviewers:
      - erunion
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
    ignore:
      - dependency-name: commander
        versions:
          - "*"

      # globby@12 is now an ESM-only package and can't be loaded here without a rewrite.
      # https://github.com/sindresorhus/globby/releases/tag/v12.0.0
      - dependency-name: globby
        versions:
          - ">= 12"
